# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-22 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0003_auto_20180621_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='msg',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='message',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
