# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-22 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0004_auto_20180622_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(blank=True, to='wall_app.Message')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wall_app.User')),
            ],
        ),
    ]
