# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0006_auto_20180622_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='wishes',
            field=models.ManyToManyField(related_name='wished_item', to='wall_app.User'),
        ),
    ]
