# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-26 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0008_user_hire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hire',
            field=models.DateField(),
        ),
    ]
